# This migration was generated by Pillowfort. It creates a default
# implementation of the token model. Modify as needed before running
# `rake db:migrate`.
#
class CreatePillowfortTokens < ActiveRecord::Migration
  def change
    create_table :pillowfort_tokens do |t|
      t.integer     :resource_id,     null: false
      t.string      :type,            null: false,  default: 'session'
      t.string      :token,           null: false
      t.string      :realm,           null: false,  default: 'application'
      t.datetime    :created_at,      null: false
      t.datetime    :expires_at,      null: false
      t.datetime    :confirmed_at,    null: true
    end

    add_index :pillowfort_tokens,
                [:resource_id, :type, :realm],
                unique: true,
                name: :udx_pillowfort_tokens_on_rid_type_and_realm

    add_index :pillowfort_tokens,
                [:type, :token],
                unique: true,
                name: :udx_pillowfort_tokens_on_type_and_token
  end
end
