# This migration was generated by Pillowfort. It assumes the default
# name for authenticable model. Modify as needed before running
# `rake db:migrate`.
#
class CreatePillowfortResources < ActiveRecord::Migration[5.1]
  def change
    create_table :users do |t|
      t.string :email,            null: false
      t.string :password_digest,  null: true

      t.timestamps                null: false
    end

    add_index :users,
                [:email],
                unique: true,
                name:   :udx_users_on_email
  end
end
